### ISSUE TITLE
[Suggestion] Tree feller & Vein Miner Enchantments

### ISSUE THREAD

**Issue by SylisMC** [Tigereye504/spellbound#1]
as the title suggests, an enchantment for tree feller and vein miner. it would allow for a more "vanilla friendly" alternative to getting a straight-up tree feller/vein miner for free

**Comment by Tigereye504** [comment]
I going to refuse... at least, to make a mere tree feller. The enchantment that I'm currently putting the final touches on has so much more potential than just felling trees.
