### ISSUE TITLE
Missing Enchantment Descriptions

### ISSUE THREAD

**Issue by Techbites457** [Tigereye504/spellbound#14]
I noticed that a few enchantment descriptions are missing. The descriptions read "spellbound.ENCHANTMENT_NAME.desc", and the ones I found were "Cave-In", "Flesh Wound", and "Launching".

**Comment by Techbites457** [comment]
Noticed that it was fixed in the latest update. Thanks for the quick fix! :)

**Comment by Tigereye504** [comment]
no problem. The update also fixed a potential crash if Saturated spawned on non-player equipment, so I recommend updating sooner than later.
