### ISSUE TITLE
Jousting On Tridents is Overpowered

### ISSUE THREAD

**Issue by ZenoCoding** [Tigereye504/spellbound#17]
<img width="2048" alt="Screen Shot 2022-06-06 at 3 00 03 PM" src="https://user-images.githubusercontent.com/51522505/172248311-1e4c96dc-3475-4478-912d-771a785b6be2.png">
It's very simple. Its overpowered.

Disabling it is not compatible with Impaled, a trident mod, because it somehow only sets jousting to be incompat disabled w/ vanilla tridents.

**Comment by ZenoCoding** [comment]
> <img alt="Screen Shot 2022-06-06 at 3 00 03 PM" width="2000" src="https://user-images.githubusercontent.com/51522505/172248311-1e4c96dc-3475-4478-912d-771a785b6be2.png">
> 
> It's very simple. Its overpowered.
> Disabling it is not compatible with Impaled, a trident mod, because it somehow only sets jousting to be incompat disabled w/ vanilla tridents.

(61.92 Damage is what that reads)

**Comment by Tigereye504** [comment]
This was due to an error in Jousting's damage calculation. It is fixed in 1.9.1 for MC 1.18.2 and 1.9.2 for MC 1.19

**Comment by ZenoCoding** [comment]
Thanks!

**Comment by ZenoCoding** [comment]
@Tigereye504 Although the disabling works better now, items that previously had jousting still have it, which is a foreseeable issue that I could understand as a mod developer, so whether you wish to implement a fix is not really my concern.

Despite the calculation being somewhat fixed, with tridents not doing insane amounts of base damage whilst standing still, I still think jousting needs a nerf, as with it on a shovel sprint jumping, it did upwards of 8 hearts to a maxed netherite player, whereas a maxed netherite sword does 1 heart..
