### ISSUE TITLE
Disabling hearty enchantment ticking when it's disabled.

### ISSUE THREAD

**Issue by Rad586** [Tigereye504/spellbound#23]
1.18.2 fabric, spellbound 1.9.1
Spark profiler reported that _net.tigereye.spellbound.enchantments.protection.HeartyEnchantment.onTickAlways()_ is negatively affecting performance while I had already disabled the hearty enchantment. 
I guess it would be more performance-friendly to stop ticking when the hearty enchantment was disabled.

**Comment by Tigereye504** [comment]
Closed as moot; Hearty no longer uses a global tick as I have found a better way to detect and handle the stat change.
