### ISSUE TITLE
Touching block...

### ISSUE THREAD

**Issue by noncom** [Tigereye504/spellbound#24]
Hi! Getting a lot of "Touching block ..." messages with this mod, they really spam the console and the log hard.
Like, thousands and tousands of messages if I go exploring..

I noticed that it was a debug setting that was turned off in one of the last commits, but that version is yet not on CurseForge.

Would it be possible to update the build on the CF so that it includes that fix? 😄

**Comment by Tigereye504** [comment]
...yup, that's an oversight. I'll get it fixed promptly.

**Comment by EightBitBBQ** [comment]
Running 1.19.2 server and having the same issue. Was this ever fixed?
When multiple player around, this will hurts performance alot

**Comment by Tigereye504** [comment]
It has been, yes. I recommend updating to version 1.14.0.1, as it fixes some other bugs as well and is the last 1.19.2 version.
