### ISSUE TITLE
Request: Config file

### ISSUE THREAD

**Issue by FewerFlaws** [Tigereye504/spellbound#3]
I'd like to request a config file so that individual enchantments can be disabled and the levels available can be controlled =]

**Comment by FewerFlaws** [comment]
Furthermore, it would be much appreciated if the enchantment values could be scaled in the config file.  This is especially valueable for the trophy collector enchantments since they can scale out of control in modded environments with a great variety of rocks/mobs available.

**Comment by Neubulae** [comment]
I second this, especially if enchantments can be fine-tuned to be in/compatible with other desired enchantments

**Comment by Tigereye504** [comment]
Priority will be going to some balance and bug fixes that are currently in progress, but config files should come within the next few updates.

**Comment by Tigereye504** [comment]
Apparently 'within a few updates' meant half a year. Sorry about that.
