### ISSUE TITLE
Red-Alert's Shields Down buff is affected by remaining duration on Shields-Up buff

### ISSUE THREAD

**Issue by FewerFlaws** [Tigereye504/spellbound#5]
The shields-up buff is applied for 16 seconds in 10 second intervals.  If I take damage when the shields-up buff shows 15 seconds remaining then the shields-down buff lasts a long time.  If I take damage when the shields-up buff shows 6 seconds remaining then the shields-down buff lasts a short time.

This behaviour is odd and probably not intended.  Conceptually, the shields-up buff lasts indefinitely but is suppressed by the shields-down buff.  Shields-down should have the same duration every time it is triggered.

**Comment by Tigereye504** [comment]
Shields Down serves as a way to track the remaining cooldown on a '0 layer' shield. If you lose your last shield one second before you would gain your next layer of shielding, shielded is replaced by one second of shields down. This is working as intended, but if other players also find this confusing I may change it.
